// src/services/steinService.ts
const BASE_URL = 'https://api.steinhq.com/v1/storages/68312b2bc0883333659f5dfa';

const allSheets = ['ACEITEX', 'ACINDAR', 'ACINDAR-ALAMBRES', 'ALIGAS', 'ALNAT-ACOPLES RAPIDOS', 'AMBAR-HILO DE POLIPROPILENO', 'ANEMI', 'ANTARTIDA', 'ARS PLASTIC', 'ARTICULOS DE GOMA-PLASTICOS VS', 'ATITAN', 'BADEMA', 'BALDES DE ALBANIL PLASTICOS', 'BARBERO', 'BARBERO-IMPORTACION', 'BARBIJO (EXCELENTE CALIDAD)', 'BOLSAS-WORLDPLAS S.A', 'BOTAS DAMALU (USD)', 'BOTIN DE SEGURIDAD FIORE', '_BREMEN 1',  '_BREMEN 2',  '_BREMEN 3', '_BREMEN 4', '_BREMEN 5', 'CABOS.', 'CALABRO',  
'CARBIZ', 'CAUCHET-PRODUCTOS QUIMICOS', 'CERAMICRUZ', 'CI-MURAT', 'CINTA DE PELIGRO', 'CINTA DE PERSIANA CL', 'CIOCCA-(MATERIALES ELECTRICOS)', 'CIOCCA-MATERIALES ELECTRICOS', 'CLAVO CABEZA DE PLOMO', 'COMET', 'CONOMETAL-PIRAMIDE', 'CORVEX', 'CRECCHIO-PRECINTOS', 'CUZCO', 'DAG', 'DE LUCA (CLAVOS)', 'DIBAPLAST', '_DOBLE A 1', '_DOBLE A 2', 'DOBLE A - DISCOS DE CORTE', 'DUKE', 'DUKE -IMPORTADO EN PESOS.', 'DUKU (ARCOS SEPARADORES Y CUNA', 'EL ABUELO', 'EL ESCUERZO', 'EL TALA', 'ESCALERAS METALICAS NEW VAL', 'ESCALERAS TARARIRA', 'EVEL', '_EVOLUTION-NEON-ROTWEILLER 1', '_EVOLUTION-NEON-ROTWEILLER 2','_EVOLUTION-NEON-ROTWEILLER 3', 'EXTENDER MP', 'EXTRAPOL S.A ( EX C-H)', 'EZETA', 'EZETA - AR LARGA COD.1200', 'EZETA AR-DECIMALES', 'EZETA-MECHAS CONICAS', 'EZETA-MECHAS SDS PLUS', 'EZETA-MECHAS VASTAGO REDUCIDO', 'F-P MAQUINAS DE SALPICAR', 'F.3', 'FAM-HASTA AGOTAR STOCK', 'FERCAS', 'FERRIMEX', 'FG-METALURGICA', 'FIELTRO FRATACHO', 'FORD', 'FORD (LANZAMIENTO FEBRERO 2017', 'FORTEX-ADHESIVOS S.R.L', 'FRATACHOS', 'FREPLAST-MANGUERA RIEGO-PVC-PR', 'GASSMANN-TERMOFUSORAS', 'GHERARDI', 'GRAN PRESION', 'GUANTES', 'HASTA AGOTAR STOCK', 'ITEPA S.A', 'IZAJES-IMPORTACION', 'J-R CLIPS P.BATERIA-PINZA MAZA', 'K-10', 'KLEBER-SIERRAS Y DISCOS', 'KUWAIT', 'LA ESPERANZA (HILOS Y SOGAS)', 'LA ESPERANZA (TANZA USD)', 'LA HACENDOSA- VIRUTA,TANZA', 'LLUSA', 'MACHETE', 'MAGICLICK', 'MARCAFACIL', 'MATA-RAT', 'MDG PRODUCTOS ELECTRICOS', 'MEMBRANA AUTOADHESIVA', 'METALURGICA ALVAREZ', 'MOISES', 'MOISES CABOS', 'MONKOTO', 'MOR (ESCALERAS DE ALUMINIO) EN', 'MULTICADENAS', 'MULTIMAXI', 'N.C.D', 'NAVEGANTE', 'NEIKE', 'OPTIMO', 'PAPAGNO (CAJAS DE HERRAMIENTAS', 'PARTS S.A', 'PENETRIT', 'PERROTTA', 'PINAS', 'PLASTICOS EL PARQUE', 'PLASTICOS FLOMAR', 'PLASTIRRABIT', 'PLASTIRRABIT IMPORTADO', 'POLIETILENO Y FILM STRETCH', 'POLITEN (TENDEDEROS)', 'POP-ARGENRAP', 'PREGO (GRIFERIA)', 'PROTEGER', 'PY FIJACIONES S.A', 'RAKETA', 'RE-FLEX (CABLES ELECTRICOS)', 'RE-PLAST (CAJAS PLASTICAS)', 'REJAS Y TAPAS AC.INOX.C.MARCO', 'ROA', 'ROLLS', 'ROOLS-P.REBAJADOS 40 % HASTA A', 'ROSARPIN', 'ROTTWEILER DISCOS Y SIERRAS', 'RUEDAS DE GOMA Y PLASTICAS', 'SABATINO', 'SANOGAS', 'SANTA JUANA', 'SANTORO', 'SAVICAR', '_SC-METALURGICA 1','_SC-METALURGICA 2', 'SCOGAR', 'SECADORES ETERNO', 'SEGUGOMA', 'SEGURIDAD INDUSTRIAL', 'SILVER SHADOW (CAJASGAVETEROS', 'SIN PAR', 'SIPAR-CLAVOS', 'SOLYON (EN PESOS)', 'SOLYON (USD)', 'STOP', 'T.M.L.H', 'TABYPLAST', 'TACO-LATEX', 'TACSA (DOLARIZADO)', 'TALLERES FUMACA', 'TANZA-GRILLON (USD)', 'TAPABOCAS', 'TEJIDOS HEXAGONALES', 'TOOL MEN', 'TOR (ENROLLADORES Y TORNIQUETE', 'TORIANO', 'TOTH', 'TYROLIT', 'TYROLIT-BASIC', 'TYROLIT-XPERT TOOLS', 'UHU ADHESIVOS', 'URBAN FRESH', 'VARIOS', 'VIGGO - SOPORTES PARA LED', 'VIRGA', 'VOLT (HERRAMIENTAS ELECTRICAS)', 'VOLT (LANZAMIENTO 2017) H.ELEC', 'Z.H'];

// helper para pausar
export function sleep(ms: number) {
  return new Promise(res => setTimeout(res, ms));
}

export async function fetchAllProducts() {
  return fetchProductsFromSheets(allSheets);
}

export async function fetchProductsByBrand(brand: string) {
  const res = await fetch(`${BASE_URL}/${encodeURIComponent(brand)}`);
  if (!res.ok) throw new Error('No se pudieron obtener los productos');
  return res.json(); // Array de filas con { Marca, Código, Descripción, Precio, 'img url' }
}

export async function fetchProductsFromSheet(sheetName: string) {
  const res = await fetch(`${BASE_URL}/${encodeURIComponent(sheetName)}`);
  if (!res.ok) throw new Error(`Error al obtener hoja ${sheetName}`);
  return res.json();
}

// NUEVO: para obtener productos de múltiples hojas
export async function fetchProductsFromSheets(sheetNames: string[]) {
  const all: any[] = [];

  for (const name of sheetNames) {
    try {
      const data = await fetchProductsFromSheet(name);
      all.push(...data);
      await sleep(100)
    } catch (e) {
      console.error(`Error en la hoja ${name}:`, e);
    }
  }

  return all;
}

